export const marketSeed = [
  {
    code: "US",
    nameZh: "美国",
    nameEn: "United States",
    currency: "USD",
    vatRate: 0,
    deMinimisUsd: 0,
    demandIndex: 96,
    competitionIndex: 88,
    logisticsScore: 82,
    flag: "🇺🇸",
    notes: "中国产地小额免税已基本取消，需按 HS 计征关税及 301 附加税。Amazon/TikTok 需求最大，广告成本高。",
  },
  {
    code: "CA",
    nameZh: "加拿大",
    nameEn: "Canada",
    currency: "CAD",
    vatRate: 0.05,
    deMinimisUsd: 15,
    demandIndex: 72,
    competitionIndex: 64,
    logisticsScore: 78,
    flag: "🇨🇦",
    notes: "低值免税额很低。GST/HST 在多数省份叠加。适合轻小件空运专线。",
  },
  {
    code: "UK",
    nameZh: "英国",
    nameEn: "United Kingdom",
    currency: "GBP",
    vatRate: 0.2,
    deMinimisUsd: 170,
    demandIndex: 80,
    competitionIndex: 70,
    logisticsScore: 84,
    flag: "🇬🇧",
    notes: "£135 以下免关税但仍收 VAT。Amazon UK 与 TikTok UK 家居/宠物表现好。",
  },
  {
    code: "DE",
    nameZh: "德国",
    nameEn: "Germany",
    currency: "EUR",
    vatRate: 0.19,
    deMinimisUsd: 160,
    demandIndex: 86,
    competitionIndex: 74,
    logisticsScore: 88,
    flag: "🇩🇪",
    notes: "欧盟 IOSS 可代收 VAT。CE/GPSR 合规是硬门槛。家居与工具类需求稳定。",
  },
  {
    code: "FR",
    nameZh: "法国",
    nameEn: "France",
    currency: "EUR",
    vatRate: 0.2,
    deMinimisUsd: 160,
    demandIndex: 74,
    competitionIndex: 68,
    logisticsScore: 80,
    flag: "🇫🇷",
    notes: "VAT 20%。美妆工具、母婴、家居收纳在本地平台与 Amazon 都有空间。",
  },
  {
    code: "JP",
    nameZh: "日本",
    nameEn: "Japan",
    currency: "JPY",
    vatRate: 0.1,
    deMinimisUsd: 65,
    demandIndex: 84,
    competitionIndex: 76,
    logisticsScore: 90,
    flag: "🇯🇵",
    notes: "品质与包装要求高，退货率低。PSE/计量等认证视品类而定。客单价可做高。",
  },
  {
    code: "AU",
    nameZh: "澳大利亚",
    nameEn: "Australia",
    currency: "AUD",
    vatRate: 0.1,
    deMinimisUsd: 650,
    demandIndex: 70,
    competitionIndex: 58,
    logisticsScore: 72,
    flag: "🇦🇺",
    notes: "AUD 1000 以下免关税但仍可能收 GST。运距长，海运性价比高。户外/宠物强。",
  },
  {
    code: "SG",
    nameZh: "新加坡",
    nameEn: "Singapore",
    currency: "SGD",
    vatRate: 0.09,
    deMinimisUsd: 300,
    demandIndex: 62,
    competitionIndex: 55,
    logisticsScore: 94,
    flag: "🇸🇬",
    notes: "关税近乎为零，GST 9%。适合作为东南亚转运与高客单测试市场。",
  },
  {
    code: "AE",
    nameZh: "阿联酋",
    nameEn: "United Arab Emirates",
    currency: "AED",
    vatRate: 0.05,
    deMinimisUsd: 270,
    demandIndex: 68,
    competitionIndex: 50,
    logisticsScore: 86,
    flag: "🇦🇪",
    notes: "VAT 5%，进口关税常见 5%。Noon / Amazon.ae 电子与家居增长快。",
  },
  {
    code: "MX",
    nameZh: "墨西哥",
    nameEn: "Mexico",
    currency: "MXN",
    vatRate: 0.16,
    deMinimisUsd: 50,
    demandIndex: 78,
    competitionIndex: 48,
    logisticsScore: 60,
    flag: "🇲🇽",
    notes: "Mercado Libre 需求旺盛、竞争低于美国。清关与最后一公里波动大。",
  },
  {
    code: "KR",
    nameZh: "韩国",
    nameEn: "South Korea",
    currency: "KRW",
    vatRate: 0.1,
    deMinimisUsd: 150,
    demandIndex: 73,
    competitionIndex: 72,
    logisticsScore: 88,
    flag: "🇰🇷",
    notes: "美妆工具与数码配件接受度高，KC 认证视品类。客单价中高。",
  },
  {
    code: "BR",
    nameZh: "巴西",
    nameEn: "Brazil",
    currency: "BRL",
    vatRate: 0.17,
    deMinimisUsd: 50,
    demandIndex: 81,
    competitionIndex: 44,
    logisticsScore: 52,
    flag: "🇧🇷",
    notes: "税负复杂（ICMS 等），但本地供给不足，轻小件差价往往可观。",
  },
];

export const fxSeed = [
  { currency: "CNY", cnyPerUnit: 1 },
  { currency: "USD", cnyPerUnit: 7.25 },
  { currency: "EUR", cnyPerUnit: 7.85 },
  { currency: "GBP", cnyPerUnit: 9.2 },
  { currency: "JPY", cnyPerUnit: 0.048 },
  { currency: "AUD", cnyPerUnit: 4.7 },
  { currency: "SGD", cnyPerUnit: 5.4 },
  { currency: "AED", cnyPerUnit: 1.97 },
  { currency: "CAD", cnyPerUnit: 5.3 },
  { currency: "MXN", cnyPerUnit: 0.36 },
  { currency: "KRW", cnyPerUnit: 0.0052 },
  { currency: "BRL", cnyPerUnit: 1.25 },
];

export const categorySeed = [
  {
    slug: "3c-accessories",
    nameZh: "3C 数码配件",
    nameEn: "Consumer electronics accessories",
    hsChapter: "85",
    typicalHs: "8518.30",
    weightClass: "light",
    riskLevel: "medium",
    recommended: 1,
    reason: "重量轻、客单价高、复购快。需避开品牌专利与电池空运限制。",
  },
  {
    slug: "home-storage",
    nameZh: "家居收纳",
    nameEn: "Home storage",
    hsChapter: "39",
    typicalHs: "3924.90",
    weightClass: "medium",
    riskLevel: "low",
    recommended: 1,
    reason: "非标品、专利少、多国刚需。体积是运费关键，适合海运备货。",
  },
  {
    slug: "pet",
    nameZh: "宠物用品",
    nameEn: "Pet supplies",
    hsChapter: "39",
    typicalHs: "3924.90",
    weightClass: "medium",
    riskLevel: "low",
    recommended: 1,
    reason: "美欧澳需求持续增长，内容电商好做，合规相对简单。",
  },
  {
    slug: "fitness",
    nameZh: "运动健身",
    nameEn: "Sports & fitness",
    hsChapter: "95",
    typicalHs: "9506.91",
    weightClass: "medium",
    riskLevel: "low",
    recommended: 1,
    reason: "季节性清晰，阻力带/瑜伽辅具重量可控，差价稳定。",
  },
  {
    slug: "beauty-tools",
    nameZh: "美妆工具",
    nameEn: "Beauty tools",
    hsChapter: "96",
    typicalHs: "9603.30",
    weightClass: "light",
    riskLevel: "medium",
    recommended: 1,
    reason: "体积小、视觉转化高。避免宣称医疗功效，注意材质合规。",
  },
  {
    slug: "baby",
    nameZh: "母婴用品",
    nameEn: "Baby products",
    hsChapter: "39",
    typicalHs: "3924.90",
    weightClass: "light",
    riskLevel: "medium",
    recommended: 1,
    reason: "客单价与复购都不错，但安全标准（CPC/EN）必须前置。",
  },
  {
    slug: "outdoor",
    nameZh: "户外露营",
    nameEn: "Outdoor & camping",
    hsChapter: "85",
    typicalHs: "8513.10",
    weightClass: "medium",
    riskLevel: "medium",
    recommended: 1,
    reason: "澳美欧季节爆款明显。含电池灯具需走合格空运渠道。",
  },
  {
    slug: "kitchen",
    nameZh: "厨房小工具",
    nameEn: "Kitchen gadgets",
    hsChapter: "39",
    typicalHs: "3924.10",
    weightClass: "light",
    riskLevel: "low",
    recommended: 1,
    reason: "内容平台易出单，食品接触材料需 FDA/LFGB。",
  },
  {
    slug: "auto",
    nameZh: "汽车配件",
    nameEn: "Auto accessories",
    hsChapter: "87",
    typicalHs: "8708.29",
    weightClass: "light",
    riskLevel: "medium",
    recommended: 1,
    reason: "车载支架/收纳差价大。避开安全件与 OEM 商标。",
  },
  {
    slug: "office",
    nameZh: "办公数码",
    nameEn: "Office & desk",
    hsChapter: "94",
    typicalHs: "9403.20",
    weightClass: "medium",
    riskLevel: "low",
    recommended: 1,
    reason: "居家办公刚需，灯具与支架可做差异化外观。",
  },
];

export const productSeed = [
  {
    sku: "TD-EB-001",
    nameZh: "私模半入耳蓝牙耳机",
    nameEn: "Private-mold TWS earbuds",
    categorySlug: "3c-accessories",
    hsCode: "8518.30",
    weightKg: 0.085,
    volumeCbm: 0.0004,
    sourcePriceCny: 28.5,
    moq: 50,
    supplierName: "深圳龙华某声学厂",
    supplierPlatform: "1688",
    leadDays: 12,
    demandScore: 88,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/8437210/pexels-photo-8437210.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "非品牌私模，Type-C 充电仓，适合 Amazon / TikTok 铺货。需确认蓝牙 ID 与电池空运报告。",
    certifications: "CE, FCC, UN38.3",
    ipRisk: "medium",
  },
  {
    sku: "TD-HUB-014",
    nameZh: "七合一 USB-C 扩展坞",
    nameEn: "7-in-1 USB-C hub",
    categorySlug: "3c-accessories",
    hsCode: "8471.80",
    weightKg: 0.12,
    volumeCbm: 0.0005,
    sourcePriceCny: 42,
    moq: 30,
    supplierName: "东莞清溪电子",
    supplierPlatform: "1688",
    leadDays: 10,
    demandScore: 79,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/4195404/pexels-photo-4195404.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "HDMI 4K + PD 充电。芯片方案需避开专利接口描述，包装走中性。",
    certifications: "CE, FCC, RoHS",
    ipRisk: "medium",
  },
  {
    sku: "TD-CHG-022",
    nameZh: "三合一磁吸无线充",
    nameEn: "3-in-1 magnetic wireless charger",
    categorySlug: "3c-accessories",
    hsCode: "8504.40",
    weightKg: 0.22,
    volumeCbm: 0.001,
    sourcePriceCny: 36,
    moq: 40,
    supplierName: "深圳宝安充电工厂",
    supplierPlatform: "Alibaba",
    leadDays: 15,
    demandScore: 83,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "避开 MagSafe 商标，走磁吸通用描述。欧美节日礼品属性强。",
    certifications: "CE, FCC, Qi",
    ipRisk: "high",
  },
  {
    sku: "TD-CBL-008",
    nameZh: "编织磁吸充电线套装",
    nameEn: "Braided magnetic cable set",
    categorySlug: "3c-accessories",
    hsCode: "8544.42",
    weightKg: 0.09,
    volumeCbm: 0.00035,
    sourcePriceCny: 9.8,
    moq: 100,
    supplierName: "惠州线材厂",
    supplierPlatform: "1688",
    leadDays: 7,
    demandScore: 74,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/4195407/pexels-photo-4195407.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "低客单测款神器，利润看运费。适合多国铺货，但需控退货。",
    certifications: "CE, RoHS",
    ipRisk: "low",
  },
  {
    sku: "TD-ORG-031",
    nameZh: "可叠加工具抽屉收纳盒",
    nameEn: "Stackable drawer organizer",
    categorySlug: "home-storage",
    hsCode: "3924.90",
    weightKg: 0.48,
    volumeCbm: 0.006,
    sourcePriceCny: 16.5,
    moq: 80,
    supplierName: "台州注塑厂",
    supplierPlatform: "1688",
    leadDays: 18,
    demandScore: 81,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "体积偏大，快递会吃掉差价。建议海运海外仓后再上 Amazon。",
    certifications: "无特殊",
    ipRisk: "low",
  },
  {
    sku: "TD-LAMP-019",
    nameZh: "护眼折叠台灯",
    nameEn: "Folding LED desk lamp",
    categorySlug: "office",
    hsCode: "9405.21",
    weightKg: 0.62,
    volumeCbm: 0.004,
    sourcePriceCny: 39,
    moq: 50,
    supplierName: "中山灯具厂",
    supplierPlatform: "1688",
    leadDays: 16,
    demandScore: 77,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/29283981/pexels-photo-29283981.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "日韩德对色温与频闪敏感，需提供光谱报告。适合独立站礼品线。",
    certifications: "CE, UKCA, PSE",
    ipRisk: "low",
  },
  {
    sku: "TD-STAND-006",
    nameZh: "铝合金折叠笔记本支架",
    nameEn: "Folding aluminum laptop stand",
    categorySlug: "office",
    hsCode: "7616.99",
    weightKg: 0.55,
    volumeCbm: 0.0022,
    sourcePriceCny: 31,
    moq: 40,
    supplierName: "佛山五金厂",
    supplierPlatform: "1688",
    leadDays: 14,
    demandScore: 80,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/4195404/pexels-photo-4195404.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "外观差异化即可避开专利。欧美办公配件长销。",
    certifications: "无特殊",
    ipRisk: "low",
  },
  {
    sku: "TD-PET-044",
    nameZh: "慢食防噎宠物碗",
    nameEn: "Slow-feeder pet bowl",
    categorySlug: "pet",
    hsCode: "3924.90",
    weightKg: 0.28,
    volumeCbm: 0.002,
    sourcePriceCny: 12.6,
    moq: 60,
    supplierName: "宁波宠物用品厂",
    supplierPlatform: "1688",
    leadDays: 11,
    demandScore: 90,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/38398913/pexels-photo-38398913.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "内容电商爆款结构，FDA 食品接触级 PP。美澳英需求都强。",
    certifications: "FDA, LFGB",
    ipRisk: "low",
  },
  {
    sku: "TD-PET-051",
    nameZh: "五指宠物洗澡手套",
    nameEn: "Pet grooming glove",
    categorySlug: "pet",
    hsCode: "6307.90",
    weightKg: 0.08,
    volumeCbm: 0.0005,
    sourcePriceCny: 6.4,
    moq: 120,
    supplierName: "义乌日用厂",
    supplierPlatform: "1688",
    leadDays: 8,
    demandScore: 76,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/38530572/pexels-photo-38530572.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "极轻小件，快递利润可观。竞争中等，靠颜色与包装出差异。",
    certifications: "无特殊",
    ipRisk: "low",
  },
  {
    sku: "TD-YG-011",
    nameZh: "TPE 瑜伽垫 6mm",
    nameEn: "6mm TPE yoga mat",
    categorySlug: "fitness",
    hsCode: "9506.91",
    weightKg: 0.85,
    volumeCbm: 0.007,
    sourcePriceCny: 22,
    moq: 50,
    supplierName: "扬州运动用品",
    supplierPlatform: "1688",
    leadDays: 20,
    demandScore: 71,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/6932262/pexels-photo-6932262.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "体积大，国际快递通常亏。海运海外仓后利润才成立。",
    certifications: "无特殊",
    ipRisk: "low",
  },
  {
    sku: "TD-RB-003",
    nameZh: "乳胶阻力带五件套",
    nameEn: "Latex resistance band set",
    categorySlug: "fitness",
    hsCode: "9506.91",
    weightKg: 0.32,
    volumeCbm: 0.0014,
    sourcePriceCny: 14.8,
    moq: 80,
    supplierName: "东莞运动橡塑",
    supplierPlatform: "1688",
    leadDays: 12,
    demandScore: 85,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/36400032/pexels-photo-36400032.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "重量适中，空运也能做。附教学卡可提高客单。",
    certifications: "无特殊",
    ipRisk: "low",
  },
  {
    sku: "TD-BT-017",
    nameZh: "316 不锈钢保温杯 500ml",
    nameEn: "500ml stainless tumbler",
    categorySlug: "kitchen",
    hsCode: "9617.00",
    weightKg: 0.38,
    volumeCbm: 0.0016,
    sourcePriceCny: 19.9,
    moq: 60,
    supplierName: "永康杯壶厂",
    supplierPlatform: "1688",
    leadDays: 15,
    demandScore: 82,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/12115336/pexels-photo-12115336.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "礼品与通勤双场景。注意真空壶 HS 与部分市场反倾销。",
    certifications: "FDA, LFGB",
    ipRisk: "low",
  },
  {
    sku: "TD-KIT-027",
    nameZh: "食品级硅胶厨具五件套",
    nameEn: "Silicone kitchen utensil set",
    categorySlug: "kitchen",
    hsCode: "3924.10",
    weightKg: 0.42,
    volumeCbm: 0.0024,
    sourcePriceCny: 18.2,
    moq: 70,
    supplierName: "深圳硅胶厂",
    supplierPlatform: "1688",
    leadDays: 13,
    demandScore: 75,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/36573009/pexels-photo-36573009.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "颜色款好拍短视频。必须食品接触级检测。",
    certifications: "FDA, LFGB",
    ipRisk: "low",
  },
  {
    sku: "TD-BLD-009",
    nameZh: "便携榨汁杯",
    nameEn: "Portable blender bottle",
    categorySlug: "kitchen",
    hsCode: "8509.40",
    weightKg: 0.58,
    volumeCbm: 0.0028,
    sourcePriceCny: 33,
    moq: 40,
    supplierName: "佛山小家电",
    supplierPlatform: "Alibaba",
    leadDays: 18,
    demandScore: 69,
    trend: "falling",
    imageUrl: "https://images.pexels.com/photos/33434017/pexels-photo-33434017.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "含电机与电池，认证与空运成本高，仅建议海运测款。",
    certifications: "CE, FCC, FDA, UN38.3",
    ipRisk: "medium",
  },
  {
    sku: "TD-BEA-012",
    nameZh: "洁面按摩仪",
    nameEn: "Facial cleansing brush",
    categorySlug: "beauty-tools",
    hsCode: "9603.30",
    weightKg: 0.14,
    volumeCbm: 0.0006,
    sourcePriceCny: 21,
    moq: 50,
    supplierName: "广州美妆工具厂",
    supplierPlatform: "1688",
    leadDays: 12,
    demandScore: 84,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/6634646/pexels-photo-6634646.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "日韩美市场内容转化高。避免医疗宣称，走美容工具。",
    certifications: "CE, FCC",
    ipRisk: "low",
  },
  {
    sku: "TD-DRY-004",
    nameZh: "高速负离子迷你吹风机",
    nameEn: "Mini high-speed hair dryer",
    categorySlug: "beauty-tools",
    hsCode: "8516.31",
    weightKg: 0.46,
    volumeCbm: 0.002,
    sourcePriceCny: 58,
    moq: 30,
    supplierName: "东莞个护电器",
    supplierPlatform: "Alibaba",
    leadDays: 20,
    demandScore: 73,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/14453472/pexels-photo-14453472.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "电压与插头按目标国切换。利润可观但认证费用要摊销。",
    certifications: "CE, UKCA, PSE, ETL",
    ipRisk: "medium",
  },
  {
    sku: "TD-BABY-021",
    nameZh: "硅胶围兜可收纳",
    nameEn: "Roll-up silicone baby bib",
    categorySlug: "baby",
    hsCode: "3924.90",
    weightKg: 0.11,
    volumeCbm: 0.0007,
    sourcePriceCny: 8.9,
    moq: 100,
    supplierName: "扬州母婴硅胶",
    supplierPlatform: "1688",
    leadDays: 10,
    demandScore: 79,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/32299511/pexels-photo-32299511.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "轻小高复购。美国需 CPC，欧盟需 EN 71 / GPSR。",
    certifications: "CPC, EN71, FDA",
    ipRisk: "low",
  },
  {
    sku: "TD-OUT-016",
    nameZh: "可充电露营灯",
    nameEn: "Rechargeable camping lantern",
    categorySlug: "outdoor",
    hsCode: "8513.10",
    weightKg: 0.35,
    volumeCbm: 0.0018,
    sourcePriceCny: 24,
    moq: 50,
    supplierName: "宁波户外灯具",
    supplierPlatform: "1688",
    leadDays: 14,
    demandScore: 78,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/12115431/pexels-photo-12115431.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "澳美季节性强。电池容量决定空运可行性。",
    certifications: "CE, FCC, UN38.3",
    ipRisk: "low",
  },
  {
    sku: "TD-AUTO-002",
    nameZh: "出风口磁吸车载支架",
    nameEn: "Magnetic car vent mount",
    categorySlug: "auto",
    hsCode: "8708.29",
    weightKg: 0.1,
    volumeCbm: 0.00045,
    sourcePriceCny: 9.5,
    moq: 100,
    supplierName: "深圳车品厂",
    supplierPlatform: "1688",
    leadDays: 8,
    demandScore: 87,
    trend: "rising",
    imageUrl: "https://images.pexels.com/photos/11334986/pexels-photo-11334986.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "经典轻小高差价品。避开品牌车标与 MagSafe 字样。",
    certifications: "CE",
    ipRisk: "medium",
  },
  {
    sku: "TD-SHAVE-018",
    nameZh: "便携电动剃须刀",
    nameEn: "Travel electric shaver",
    categorySlug: "beauty-tools",
    hsCode: "8510.10",
    weightKg: 0.18,
    volumeCbm: 0.0007,
    sourcePriceCny: 29,
    moq: 40,
    supplierName: "温州个护电器",
    supplierPlatform: "1688",
    leadDays: 16,
    demandScore: 72,
    trend: "stable",
    imageUrl: "https://images.pexels.com/photos/10359950/pexels-photo-10359950.jpeg?auto=compress&cs=tinysrgb&w=900",
    description: "差旅场景清晰。刀网寿命与噪音是评测关键。",
    certifications: "CE, FCC, PSE",
    ipRisk: "low",
  },
];

type ListingTemplate = {
  sku: string;
  market: string;
  platform: string;
  sellPrice: number;
  monthlySales: number;
  reviewCount: number;
  rating: number;
  competition: number;
  bsr: number;
};

export const listingSeed: ListingTemplate[] = [
  { sku: "TD-EB-001", market: "US", platform: "Amazon", sellPrice: 19.99, monthlySales: 2400, reviewCount: 1820, rating: 4.4, competition: 78, bsr: 4200 },
  { sku: "TD-EB-001", market: "DE", platform: "Amazon", sellPrice: 21.9, monthlySales: 980, reviewCount: 640, rating: 4.3, competition: 70, bsr: 6100 },
  { sku: "TD-EB-001", market: "JP", platform: "Amazon", sellPrice: 2480, monthlySales: 760, reviewCount: 410, rating: 4.2, competition: 74, bsr: 5300 },
  { sku: "TD-EB-001", market: "AE", platform: "Noon", sellPrice: 69, monthlySales: 420, reviewCount: 190, rating: 4.3, competition: 48, bsr: 1800 },
  { sku: "TD-HUB-014", market: "US", platform: "Amazon", sellPrice: 29.99, monthlySales: 1500, reviewCount: 990, rating: 4.5, competition: 72, bsr: 3800 },
  { sku: "TD-HUB-014", market: "UK", platform: "Amazon", sellPrice: 24.99, monthlySales: 540, reviewCount: 320, rating: 4.4, competition: 66, bsr: 4500 },
  { sku: "TD-HUB-014", market: "DE", platform: "Amazon", sellPrice: 27.9, monthlySales: 610, reviewCount: 280, rating: 4.4, competition: 68, bsr: 5200 },
  { sku: "TD-CHG-022", market: "US", platform: "Amazon", sellPrice: 32.99, monthlySales: 1800, reviewCount: 2100, rating: 4.5, competition: 82, bsr: 2100 },
  { sku: "TD-CHG-022", market: "JP", platform: "Amazon", sellPrice: 3980, monthlySales: 520, reviewCount: 260, rating: 4.3, competition: 70, bsr: 3400 },
  { sku: "TD-CHG-022", market: "KR", platform: "Coupang", sellPrice: 39000, monthlySales: 390, reviewCount: 180, rating: 4.4, competition: 60, bsr: 2200 },
  { sku: "TD-CBL-008", market: "US", platform: "TikTok Shop", sellPrice: 9.99, monthlySales: 5200, reviewCount: 3400, rating: 4.2, competition: 90, bsr: 900 },
  { sku: "TD-CBL-008", market: "MX", platform: "Mercado Libre", sellPrice: 199, monthlySales: 1600, reviewCount: 540, rating: 4.3, competition: 40, bsr: 700 },
  { sku: "TD-CBL-008", market: "BR", platform: "Mercado Libre", sellPrice: 49.9, monthlySales: 2100, reviewCount: 880, rating: 4.1, competition: 38, bsr: 650 },
  { sku: "TD-ORG-031", market: "US", platform: "Amazon", sellPrice: 18.99, monthlySales: 1300, reviewCount: 760, rating: 4.6, competition: 64, bsr: 5600 },
  { sku: "TD-ORG-031", market: "DE", platform: "Amazon", sellPrice: 16.99, monthlySales: 870, reviewCount: 410, rating: 4.5, competition: 58, bsr: 4300 },
  { sku: "TD-ORG-031", market: "AU", platform: "Amazon", sellPrice: 24.9, monthlySales: 310, reviewCount: 140, rating: 4.5, competition: 44, bsr: 2100 },
  { sku: "TD-LAMP-019", market: "JP", platform: "Amazon", sellPrice: 3980, monthlySales: 640, reviewCount: 300, rating: 4.4, competition: 62, bsr: 2800 },
  { sku: "TD-LAMP-019", market: "DE", platform: "Amazon", sellPrice: 29.99, monthlySales: 480, reviewCount: 210, rating: 4.3, competition: 60, bsr: 6100 },
  { sku: "TD-LAMP-019", market: "US", platform: "Shopify", sellPrice: 34.0, monthlySales: 260, reviewCount: 90, rating: 4.7, competition: 50, bsr: 12000 },
  { sku: "TD-STAND-006", market: "US", platform: "Amazon", sellPrice: 26.99, monthlySales: 1700, reviewCount: 1540, rating: 4.6, competition: 69, bsr: 2400 },
  { sku: "TD-STAND-006", market: "UK", platform: "Amazon", sellPrice: 21.99, monthlySales: 620, reviewCount: 280, rating: 4.5, competition: 61, bsr: 3900 },
  { sku: "TD-STAND-006", market: "SG", platform: "Shopee", sellPrice: 29.9, monthlySales: 210, reviewCount: 95, rating: 4.6, competition: 42, bsr: 800 },
  { sku: "TD-PET-044", market: "US", platform: "Amazon", sellPrice: 16.99, monthlySales: 3100, reviewCount: 4200, rating: 4.7, competition: 66, bsr: 980 },
  { sku: "TD-PET-044", market: "UK", platform: "Amazon", sellPrice: 14.99, monthlySales: 890, reviewCount: 640, rating: 4.6, competition: 55, bsr: 1500 },
  { sku: "TD-PET-044", market: "AU", platform: "Amazon", sellPrice: 22.99, monthlySales: 540, reviewCount: 310, rating: 4.6, competition: 40, bsr: 720 },
  { sku: "TD-PET-044", market: "DE", platform: "Amazon", sellPrice: 15.99, monthlySales: 760, reviewCount: 430, rating: 4.5, competition: 52, bsr: 2100 },
  { sku: "TD-PET-051", market: "US", platform: "TikTok Shop", sellPrice: 8.99, monthlySales: 4400, reviewCount: 1900, rating: 4.3, competition: 74, bsr: 1100 },
  { sku: "TD-PET-051", market: "JP", platform: "Amazon", sellPrice: 1280, monthlySales: 980, reviewCount: 520, rating: 4.4, competition: 58, bsr: 1600 },
  { sku: "TD-PET-051", market: "CA", platform: "Amazon", sellPrice: 11.99, monthlySales: 430, reviewCount: 180, rating: 4.3, competition: 50, bsr: 2400 },
  { sku: "TD-YG-011", market: "US", platform: "Amazon", sellPrice: 24.99, monthlySales: 900, reviewCount: 1100, rating: 4.5, competition: 80, bsr: 4700 },
  { sku: "TD-YG-011", market: "DE", platform: "Amazon", sellPrice: 22.9, monthlySales: 410, reviewCount: 260, rating: 4.4, competition: 68, bsr: 5200 },
  { sku: "TD-RB-003", market: "US", platform: "Amazon", sellPrice: 18.99, monthlySales: 2600, reviewCount: 3300, rating: 4.6, competition: 71, bsr: 1600 },
  { sku: "TD-RB-003", market: "UK", platform: "Amazon", sellPrice: 15.99, monthlySales: 720, reviewCount: 410, rating: 4.5, competition: 60, bsr: 2300 },
  { sku: "TD-RB-003", market: "MX", platform: "Mercado Libre", sellPrice: 349, monthlySales: 880, reviewCount: 240, rating: 4.4, competition: 36, bsr: 540 },
  { sku: "TD-BT-017", market: "US", platform: "Amazon", sellPrice: 22.99, monthlySales: 1900, reviewCount: 2700, rating: 4.6, competition: 77, bsr: 1900 },
  { sku: "TD-BT-017", market: "JP", platform: "Amazon", sellPrice: 2980, monthlySales: 540, reviewCount: 300, rating: 4.5, competition: 65, bsr: 2500 },
  { sku: "TD-BT-017", market: "AE", platform: "Amazon", sellPrice: 79, monthlySales: 260, reviewCount: 90, rating: 4.4, competition: 42, bsr: 1400 },
  { sku: "TD-KIT-027", market: "DE", platform: "Amazon", sellPrice: 17.99, monthlySales: 680, reviewCount: 350, rating: 4.5, competition: 54, bsr: 3100 },
  { sku: "TD-KIT-027", market: "FR", platform: "Amazon", sellPrice: 18.9, monthlySales: 510, reviewCount: 220, rating: 4.4, competition: 50, bsr: 2800 },
  { sku: "TD-KIT-027", market: "US", platform: "Amazon", sellPrice: 19.99, monthlySales: 1100, reviewCount: 640, rating: 4.5, competition: 63, bsr: 4400 },
  { sku: "TD-BLD-009", market: "US", platform: "Amazon", sellPrice: 29.99, monthlySales: 430, reviewCount: 510, rating: 4.1, competition: 84, bsr: 9800 },
  { sku: "TD-BLD-009", market: "AU", platform: "Amazon", sellPrice: 39.99, monthlySales: 180, reviewCount: 90, rating: 4.2, competition: 55, bsr: 3600 },
  { sku: "TD-BEA-012", market: "US", platform: "TikTok Shop", sellPrice: 18.99, monthlySales: 2800, reviewCount: 1500, rating: 4.5, competition: 68, bsr: 1300 },
  { sku: "TD-BEA-012", market: "KR", platform: "Coupang", sellPrice: 24900, monthlySales: 720, reviewCount: 410, rating: 4.6, competition: 58, bsr: 900 },
  { sku: "TD-BEA-012", market: "JP", platform: "Amazon", sellPrice: 2480, monthlySales: 610, reviewCount: 280, rating: 4.4, competition: 62, bsr: 2100 },
  { sku: "TD-DRY-004", market: "US", platform: "Amazon", sellPrice: 49.99, monthlySales: 860, reviewCount: 720, rating: 4.4, competition: 73, bsr: 3400 },
  { sku: "TD-DRY-004", market: "DE", platform: "Amazon", sellPrice: 44.9, monthlySales: 310, reviewCount: 140, rating: 4.3, competition: 60, bsr: 5600 },
  { sku: "TD-DRY-004", market: "JP", platform: "Amazon", sellPrice: 6980, monthlySales: 240, reviewCount: 110, rating: 4.2, competition: 66, bsr: 4800 },
  { sku: "TD-BABY-021", market: "US", platform: "Amazon", sellPrice: 12.99, monthlySales: 2200, reviewCount: 1800, rating: 4.7, competition: 59, bsr: 1700 },
  { sku: "TD-BABY-021", market: "UK", platform: "Amazon", sellPrice: 9.99, monthlySales: 760, reviewCount: 430, rating: 4.6, competition: 48, bsr: 1400 },
  { sku: "TD-BABY-021", market: "FR", platform: "Amazon", sellPrice: 11.9, monthlySales: 540, reviewCount: 210, rating: 4.5, competition: 46, bsr: 1900 },
  { sku: "TD-OUT-016", market: "US", platform: "Amazon", sellPrice: 23.99, monthlySales: 1400, reviewCount: 980, rating: 4.5, competition: 61, bsr: 2600 },
  { sku: "TD-OUT-016", market: "AU", platform: "Amazon", sellPrice: 32.99, monthlySales: 620, reviewCount: 340, rating: 4.6, competition: 38, bsr: 890 },
  { sku: "TD-OUT-016", market: "CA", platform: "Amazon", sellPrice: 27.99, monthlySales: 280, reviewCount: 120, rating: 4.4, competition: 44, bsr: 3100 },
  { sku: "TD-AUTO-002", market: "US", platform: "Amazon", sellPrice: 15.99, monthlySales: 3600, reviewCount: 5100, rating: 4.5, competition: 80, bsr: 760 },
  { sku: "TD-AUTO-002", market: "DE", platform: "Amazon", sellPrice: 14.99, monthlySales: 1100, reviewCount: 640, rating: 4.4, competition: 70, bsr: 1800 },
  { sku: "TD-AUTO-002", market: "MX", platform: "Mercado Libre", sellPrice: 279, monthlySales: 1500, reviewCount: 430, rating: 4.4, competition: 34, bsr: 420 },
  { sku: "TD-AUTO-002", market: "AE", platform: "Noon", sellPrice: 49, monthlySales: 390, reviewCount: 150, rating: 4.3, competition: 40, bsr: 1100 },
  { sku: "TD-SHAVE-018", market: "US", platform: "Amazon", sellPrice: 24.99, monthlySales: 970, reviewCount: 680, rating: 4.3, competition: 72, bsr: 4100 },
  { sku: "TD-SHAVE-018", market: "JP", platform: "Amazon", sellPrice: 3280, monthlySales: 410, reviewCount: 190, rating: 4.2, competition: 64, bsr: 3600 },
  { sku: "TD-SHAVE-018", market: "KR", platform: "Coupang", sellPrice: 28900, monthlySales: 260, reviewCount: 110, rating: 4.3, competition: 55, bsr: 2400 },
];

export const shippingMethodSeed = [
  { method: "express", methodZh: "国际快递", notes: "DHL/UPS/FedEx 或专线快递，适合轻小件测款" },
  { method: "air", methodZh: "空运专线", notes: "商业清关空派，时效与价格折中" },
  { method: "sea_lcl", methodZh: "海运散货 LCL", notes: "按体积计费，适合备货海外仓" },
  { method: "sea_fcl", methodZh: "海运整柜 FCL", notes: "40HQ 摊到单位体积更低，适合爆款补货" },
] as const;

type ShipNum = {
  method: "express" | "air" | "sea_lcl" | "sea_fcl";
  ratePerKgUsd: number;
  ratePerCbmUsd: number;
  minChargeUsd: number;
  daysMin: number;
  daysMax: number;
};

export const shippingByMarket: Record<string, ShipNum[]> = {
  US: [
    { method: "express", ratePerKgUsd: 8.6, ratePerCbmUsd: 0, minChargeUsd: 6.5, daysMin: 4, daysMax: 8 },
    { method: "air", ratePerKgUsd: 5.4, ratePerCbmUsd: 0, minChargeUsd: 18, daysMin: 8, daysMax: 14 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 145, minChargeUsd: 55, daysMin: 22, daysMax: 35 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 78, minChargeUsd: 1200, daysMin: 24, daysMax: 38 },
  ],
  CA: [
    { method: "express", ratePerKgUsd: 9.2, ratePerCbmUsd: 0, minChargeUsd: 7, daysMin: 5, daysMax: 9 },
    { method: "air", ratePerKgUsd: 5.8, ratePerCbmUsd: 0, minChargeUsd: 20, daysMin: 9, daysMax: 16 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 155, minChargeUsd: 60, daysMin: 24, daysMax: 38 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 82, minChargeUsd: 1300, daysMin: 26, daysMax: 40 },
  ],
  UK: [
    { method: "express", ratePerKgUsd: 8.1, ratePerCbmUsd: 0, minChargeUsd: 6, daysMin: 4, daysMax: 8 },
    { method: "air", ratePerKgUsd: 5.1, ratePerCbmUsd: 0, minChargeUsd: 16, daysMin: 7, daysMax: 13 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 130, minChargeUsd: 50, daysMin: 26, daysMax: 38 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 70, minChargeUsd: 1100, daysMin: 28, daysMax: 40 },
  ],
  DE: [
    { method: "express", ratePerKgUsd: 8.0, ratePerCbmUsd: 0, minChargeUsd: 6, daysMin: 4, daysMax: 8 },
    { method: "air", ratePerKgUsd: 4.9, ratePerCbmUsd: 0, minChargeUsd: 16, daysMin: 7, daysMax: 13 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 125, minChargeUsd: 50, daysMin: 27, daysMax: 40 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 68, minChargeUsd: 1050, daysMin: 28, daysMax: 42 },
  ],
  FR: [
    { method: "express", ratePerKgUsd: 8.3, ratePerCbmUsd: 0, minChargeUsd: 6.5, daysMin: 4, daysMax: 9 },
    { method: "air", ratePerKgUsd: 5.2, ratePerCbmUsd: 0, minChargeUsd: 17, daysMin: 8, daysMax: 14 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 132, minChargeUsd: 52, daysMin: 28, daysMax: 42 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 72, minChargeUsd: 1100, daysMin: 30, daysMax: 44 },
  ],
  JP: [
    { method: "express", ratePerKgUsd: 7.2, ratePerCbmUsd: 0, minChargeUsd: 5.5, daysMin: 3, daysMax: 6 },
    { method: "air", ratePerKgUsd: 4.2, ratePerCbmUsd: 0, minChargeUsd: 14, daysMin: 5, daysMax: 10 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 95, minChargeUsd: 40, daysMin: 8, daysMax: 16 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 52, minChargeUsd: 800, daysMin: 8, daysMax: 18 },
  ],
  AU: [
    { method: "express", ratePerKgUsd: 10.5, ratePerCbmUsd: 0, minChargeUsd: 8, daysMin: 5, daysMax: 10 },
    { method: "air", ratePerKgUsd: 6.4, ratePerCbmUsd: 0, minChargeUsd: 22, daysMin: 8, daysMax: 15 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 160, minChargeUsd: 65, daysMin: 18, daysMax: 30 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 88, minChargeUsd: 1400, daysMin: 18, daysMax: 32 },
  ],
  SG: [
    { method: "express", ratePerKgUsd: 6.4, ratePerCbmUsd: 0, minChargeUsd: 5, daysMin: 3, daysMax: 6 },
    { method: "air", ratePerKgUsd: 3.6, ratePerCbmUsd: 0, minChargeUsd: 12, daysMin: 4, daysMax: 8 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 70, minChargeUsd: 30, daysMin: 6, daysMax: 12 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 40, minChargeUsd: 600, daysMin: 6, daysMax: 14 },
  ],
  AE: [
    { method: "express", ratePerKgUsd: 8.8, ratePerCbmUsd: 0, minChargeUsd: 7, daysMin: 4, daysMax: 8 },
    { method: "air", ratePerKgUsd: 5.0, ratePerCbmUsd: 0, minChargeUsd: 18, daysMin: 6, daysMax: 12 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 120, minChargeUsd: 48, daysMin: 16, daysMax: 26 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 64, minChargeUsd: 1000, daysMin: 16, daysMax: 28 },
  ],
  MX: [
    { method: "express", ratePerKgUsd: 11.2, ratePerCbmUsd: 0, minChargeUsd: 9, daysMin: 6, daysMax: 12 },
    { method: "air", ratePerKgUsd: 6.8, ratePerCbmUsd: 0, minChargeUsd: 24, daysMin: 10, daysMax: 18 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 170, minChargeUsd: 70, daysMin: 28, daysMax: 45 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 90, minChargeUsd: 1500, daysMin: 30, daysMax: 48 },
  ],
  KR: [
    { method: "express", ratePerKgUsd: 6.8, ratePerCbmUsd: 0, minChargeUsd: 5, daysMin: 3, daysMax: 6 },
    { method: "air", ratePerKgUsd: 3.9, ratePerCbmUsd: 0, minChargeUsd: 12, daysMin: 4, daysMax: 8 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 80, minChargeUsd: 32, daysMin: 4, daysMax: 10 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 44, minChargeUsd: 700, daysMin: 5, daysMax: 12 },
  ],
  BR: [
    { method: "express", ratePerKgUsd: 13.5, ratePerCbmUsd: 0, minChargeUsd: 12, daysMin: 7, daysMax: 14 },
    { method: "air", ratePerKgUsd: 8.2, ratePerCbmUsd: 0, minChargeUsd: 28, daysMin: 12, daysMax: 22 },
    { method: "sea_lcl", ratePerKgUsd: 0, ratePerCbmUsd: 190, minChargeUsd: 80, daysMin: 32, daysMax: 50 },
    { method: "sea_fcl", ratePerKgUsd: 0, ratePerCbmUsd: 98, minChargeUsd: 1700, daysMin: 34, daysMax: 52 },
  ],
};

export const tariffByHs: Record<string, Record<string, { mfn: number; extra: number; note: string }>> = {
  "8518.30": {
    US: { mfn: 0, extra: 0.075, note: "耳机音响，中国产常见 301 附加 7.5%" },
    CA: { mfn: 0, extra: 0, note: "多数消费电子 MFN 0" },
    UK: { mfn: 0, extra: 0, note: "UKGT 消费音频多为 0" },
    DE: { mfn: 0, extra: 0, note: "欧盟音频设备常见 0" },
    FR: { mfn: 0, extra: 0, note: "同欧盟" },
    JP: { mfn: 0, extra: 0, note: "WTO 信息技术产品" },
    AU: { mfn: 0, extra: 0, note: "多数消费电子 0" },
    SG: { mfn: 0, extra: 0, note: "自贸港几乎免税" },
    AE: { mfn: 0.05, extra: 0, note: "GCC 一般 5%" },
    MX: { mfn: 0.05, extra: 0, note: "视具体子目" },
    KR: { mfn: 0, extra: 0, note: "ITA 覆盖" },
    BR: { mfn: 0.16, extra: 0, note: "TEC 较高" },
  },
  "8471.80": {
    US: { mfn: 0, extra: 0.075, note: "数据处理设备零件，关注 301" },
    CA: { mfn: 0, extra: 0, note: "0" },
    UK: { mfn: 0, extra: 0, note: "0" },
    DE: { mfn: 0, extra: 0, note: "0" },
    FR: { mfn: 0, extra: 0, note: "0" },
    JP: { mfn: 0, extra: 0, note: "0" },
    AU: { mfn: 0, extra: 0, note: "0" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0, extra: 0, note: "部分 IT 0" },
    KR: { mfn: 0, extra: 0, note: "0" },
    BR: { mfn: 0.16, extra: 0, note: "高" },
  },
  "8504.40": {
    US: { mfn: 0.013, extra: 0.25, note: "电源/无线充，301 可能 25%" },
    CA: { mfn: 0, extra: 0, note: "0" },
    UK: { mfn: 0, extra: 0, note: "0" },
    DE: { mfn: 0, extra: 0, note: "0" },
    FR: { mfn: 0, extra: 0, note: "0" },
    JP: { mfn: 0, extra: 0, note: "0" },
    AU: { mfn: 0, extra: 0, note: "0" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.05, extra: 0, note: "5%" },
    KR: { mfn: 0.08, extra: 0, note: "视子目" },
    BR: { mfn: 0.18, extra: 0, note: "高" },
  },
  "8544.42": {
    US: { mfn: 0.027, extra: 0.075, note: "绝缘电线电缆" },
    CA: { mfn: 0, extra: 0, note: "0" },
    UK: { mfn: 0.032, extra: 0, note: "低关税" },
    DE: { mfn: 0.032, extra: 0, note: "欧盟约 3.3%" },
    FR: { mfn: 0.032, extra: 0, note: "同欧盟" },
    JP: { mfn: 0, extra: 0, note: "0" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.05, extra: 0, note: "5%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.16, extra: 0, note: "16%" },
  },
  "3924.90": {
    US: { mfn: 0.033, extra: 0.075, note: "塑料家庭用品" },
    CA: { mfn: 0.065, extra: 0, note: "约 6.5%" },
    UK: { mfn: 0.065, extra: 0, note: "约 6.5%" },
    DE: { mfn: 0.065, extra: 0, note: "欧盟约 6.5%" },
    FR: { mfn: 0.065, extra: 0, note: "同欧盟" },
    JP: { mfn: 0.038, extra: 0, note: "约 3.8%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.15, extra: 0, note: "塑料制品偏高" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "9405.21": {
    US: { mfn: 0.036, extra: 0.075, note: "灯具" },
    CA: { mfn: 0.07, extra: 0, note: "7%" },
    UK: { mfn: 0.027, extra: 0, note: "低" },
    DE: { mfn: 0.027, extra: 0, note: "欧盟灯具" },
    FR: { mfn: 0.027, extra: 0, note: "同欧盟" },
    JP: { mfn: 0, extra: 0, note: "部分 0" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.15, extra: 0, note: "15%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "7616.99": {
    US: { mfn: 0.025, extra: 0.075, note: "铝制品其他" },
    CA: { mfn: 0.065, extra: 0, note: "6.5%" },
    UK: { mfn: 0.06, extra: 0, note: "6%" },
    DE: { mfn: 0.06, extra: 0, note: "6%" },
    FR: { mfn: 0.06, extra: 0, note: "6%" },
    JP: { mfn: 0.03, extra: 0, note: "3%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.16, extra: 0, note: "16%" },
  },
  "6307.90": {
    US: { mfn: 0.07, extra: 0.075, note: "其他制成纺织品" },
    CA: { mfn: 0.17, extra: 0, note: "纺织偏高" },
    UK: { mfn: 0.12, extra: 0, note: "约 12%" },
    DE: { mfn: 0.12, extra: 0, note: "欧盟纺织" },
    FR: { mfn: 0.12, extra: 0, note: "同欧盟" },
    JP: { mfn: 0.06, extra: 0, note: "6%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.2, extra: 0, note: "纺织高关税" },
    KR: { mfn: 0.1, extra: 0, note: "10%" },
    BR: { mfn: 0.2, extra: 0, note: "20%" },
  },
  "9506.91": {
    US: { mfn: 0.046, extra: 0.075, note: "体操/健身器材" },
    CA: { mfn: 0.07, extra: 0, note: "7%" },
    UK: { mfn: 0.046, extra: 0, note: "4.6%" },
    DE: { mfn: 0.046, extra: 0, note: "4.6%" },
    FR: { mfn: 0.046, extra: 0, note: "4.6%" },
    JP: { mfn: 0.038, extra: 0, note: "3.8%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.2, extra: 0, note: "20%" },
  },
  "9617.00": {
    US: { mfn: 0.072, extra: 0.075, note: "真空保温容器，关注反倾销" },
    CA: { mfn: 0.07, extra: 0, note: "7%" },
    UK: { mfn: 0.07, extra: 0, note: "7%" },
    DE: { mfn: 0.07, extra: 0, note: "7%" },
    FR: { mfn: 0.07, extra: 0, note: "7%" },
    JP: { mfn: 0.038, extra: 0, note: "3.8%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.15, extra: 0, note: "15%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "3924.10": {
    US: { mfn: 0.033, extra: 0.075, note: "塑料餐具厨具" },
    CA: { mfn: 0.065, extra: 0, note: "6.5%" },
    UK: { mfn: 0.065, extra: 0, note: "6.5%" },
    DE: { mfn: 0.065, extra: 0, note: "6.5%" },
    FR: { mfn: 0.065, extra: 0, note: "6.5%" },
    JP: { mfn: 0.038, extra: 0, note: "3.8%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.15, extra: 0, note: "15%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "8509.40": {
    US: { mfn: 0.042, extra: 0.075, note: "食品研磨搅拌电器" },
    CA: { mfn: 0, extra: 0, note: "部分 0" },
    UK: { mfn: 0.022, extra: 0, note: "2.2%" },
    DE: { mfn: 0.022, extra: 0, note: "2.2%" },
    FR: { mfn: 0.022, extra: 0, note: "2.2%" },
    JP: { mfn: 0, extra: 0, note: "0" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "9603.30": {
    US: { mfn: 0, extra: 0.075, note: "化妆刷类" },
    CA: { mfn: 0.07, extra: 0, note: "7%" },
    UK: { mfn: 0.038, extra: 0, note: "3.8%" },
    DE: { mfn: 0.038, extra: 0, note: "3.8%" },
    FR: { mfn: 0.038, extra: 0, note: "3.8%" },
    JP: { mfn: 0.038, extra: 0, note: "3.8%" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "8516.31": {
    US: { mfn: 0.038, extra: 0.075, note: "电吹风" },
    CA: { mfn: 0, extra: 0, note: "0" },
    UK: { mfn: 0.027, extra: 0, note: "2.7%" },
    DE: { mfn: 0.027, extra: 0, note: "2.7%" },
    FR: { mfn: 0.027, extra: 0, note: "2.7%" },
    JP: { mfn: 0, extra: 0, note: "PSE 比关税更关键" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "KC 认证" },
    BR: { mfn: 0.2, extra: 0, note: "20%" },
  },
  "8513.10": {
    US: { mfn: 0.035, extra: 0.075, note: "手提灯具" },
    CA: { mfn: 0.07, extra: 0, note: "7%" },
    UK: { mfn: 0.027, extra: 0, note: "2.7%" },
    DE: { mfn: 0.027, extra: 0, note: "2.7%" },
    FR: { mfn: 0.027, extra: 0, note: "2.7%" },
    JP: { mfn: 0, extra: 0, note: "0" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "8708.29": {
    US: { mfn: 0.025, extra: 0.075, note: "车身零件及配件" },
    CA: { mfn: 0.06, extra: 0, note: "6%" },
    UK: { mfn: 0.045, extra: 0, note: "4.5%" },
    DE: { mfn: 0.045, extra: 0, note: "4.5%" },
    FR: { mfn: 0.045, extra: 0, note: "4.5%" },
    JP: { mfn: 0, extra: 0, note: "部分 0" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.05, extra: 0, note: "5%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.18, extra: 0, note: "18%" },
  },
  "8510.10": {
    US: { mfn: 0, extra: 0.075, note: "剃须刀" },
    CA: { mfn: 0, extra: 0, note: "0" },
    UK: { mfn: 0.022, extra: 0, note: "2.2%" },
    DE: { mfn: 0.022, extra: 0, note: "2.2%" },
    FR: { mfn: 0.022, extra: 0, note: "2.2%" },
    JP: { mfn: 0, extra: 0, note: "0" },
    AU: { mfn: 0.05, extra: 0, note: "5%" },
    SG: { mfn: 0, extra: 0, note: "0" },
    AE: { mfn: 0.05, extra: 0, note: "5%" },
    MX: { mfn: 0.1, extra: 0, note: "10%" },
    KR: { mfn: 0.08, extra: 0, note: "8%" },
    BR: { mfn: 0.16, extra: 0, note: "16%" },
  },
};

export const platformFeeSeed: { platform: string; markets: string[]; referralRate: number; fulfillmentPerUnitUsd: number; paymentFeeRate: number }[] = [
  { platform: "Amazon", markets: ["US", "CA", "UK", "DE", "FR", "JP", "AU", "AE"], referralRate: 0.15, fulfillmentPerUnitUsd: 3.45, paymentFeeRate: 0 },
  { platform: "TikTok Shop", markets: ["US", "UK"], referralRate: 0.08, fulfillmentPerUnitUsd: 2.1, paymentFeeRate: 0.02 },
  { platform: "Shopee", markets: ["SG"], referralRate: 0.08, fulfillmentPerUnitUsd: 1.2, paymentFeeRate: 0.02 },
  { platform: "Noon", markets: ["AE"], referralRate: 0.1, fulfillmentPerUnitUsd: 2.4, paymentFeeRate: 0.02 },
  { platform: "Coupang", markets: ["KR"], referralRate: 0.11, fulfillmentPerUnitUsd: 2.6, paymentFeeRate: 0.015 },
  { platform: "Mercado Libre", markets: ["MX", "BR"], referralRate: 0.16, fulfillmentPerUnitUsd: 2.9, paymentFeeRate: 0.04 },
  { platform: "Shopify", markets: ["US"], referralRate: 0, fulfillmentPerUnitUsd: 4.2, paymentFeeRate: 0.029 },
];
