/**
 * 子类目 taxonomy。
 *
 * HS 编码给到 6 位，且 hsVerified 默认为 0——这些是按品类常规给的起点，
 * 未经官方税则库逐个校验。8~10 位叶子必须用 USITC 现场解析。
 * 供应商提供的编码常常是为了最大化他自己的出口退税，与目的国认定不一致。
 *
 * complianceLevel:
 *   ok    — 无特殊准入
 *   warn  — 需证书，可测算但要提示
 *   block — 无证书禁止进入候选池（硬拦截，不是提示）
 *
 * logisticsFlag:
 *   volumetric — 抛货，体积重会吃掉全部差价，禁走快递
 *   heavy      — 重货，仅海运
 *   battery    — 带电，空运受限
 */

export type SubcategorySeed = {
  slug: string;
  categorySlug: string;
  nameZh: string;
  nameEn: string;
  hsCode: string;
  altHsCodes?: string;
  typicalWeightKg: number;
  typicalVolumeCbm: number;
  logisticsFlag?: "none" | "volumetric" | "heavy" | "battery";
  complianceLevel?: "ok" | "warn" | "block";
  requiredCerts?: string;
  note?: string;
  keywords?: string;
};

export const subcategorySeed: SubcategorySeed[] = [
  // ── 3C 数码配件 ─────────────────────────────────────────────
  {
    slug: "3c-audio",
    categorySlug: "3c-accessories",
    nameZh: "音频（TWS / 头戴 / 音箱）",
    nameEn: "Audio (TWS, headphones, speakers)",
    hsCode: "8518.30",
    altHsCodes: "8518.21,8518.22",
    typicalWeightKg: 0.085,
    typicalVolumeCbm: 0.0004,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "CE, FCC, UN38.3, 蓝牙 SIG ID",
    note: "锂电池空运需 UN38.3 与 MSDS；蓝牙需 SIG 认证 ID，否则易被平台下架。",
    keywords: "耳机,蓝牙耳机,TWS,音箱,earbuds,headphones,speaker",
  },
  {
    slug: "3c-charging",
    categorySlug: "3c-accessories",
    nameZh: "充电（氮化镓 / 无线充 / 充电宝）",
    nameEn: "Charging (GaN, wireless, power bank)",
    hsCode: "8504.40",
    altHsCodes: "8507.60",
    typicalWeightKg: 0.18,
    typicalVolumeCbm: 0.0006,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "CE, FCC, UL, PSE(日), UN38.3",
    note: "充电宝属大容量锂电，多数空运专线拒收，须走海运或电池专线。各国插头制式不同。",
    keywords: "充电器,氮化镓,无线充,充电宝,charger,power bank,GaN",
  },
  {
    slug: "3c-cable-hub",
    categorySlug: "3c-accessories",
    nameZh: "线材与扩展（数据线 / HUB / 读卡器）",
    nameEn: "Cables & hubs",
    hsCode: "8544.42",
    altHsCodes: "8471.80,8536.69",
    typicalWeightKg: 0.06,
    typicalVolumeCbm: 0.0002,
    complianceLevel: "warn",
    requiredCerts: "CE, FCC；MFi（如做苹果接口）",
    note: "苹果接口未过 MFi 属侵权，平台必下架。",
    keywords: "数据线,HUB,扩展坞,读卡器,cable,hub,adapter",
  },
  {
    slug: "3c-phone-acc",
    categorySlug: "3c-accessories",
    nameZh: "手机周边（支架 / 壳膜 / 自拍杆）",
    nameEn: "Phone accessories",
    hsCode: "3926.90",
    altHsCodes: "8479.89,7326.90",
    typicalWeightKg: 0.05,
    typicalVolumeCbm: 0.00015,
    complianceLevel: "ok",
    note: "壳膜要注意机型图案的 IP 授权。",
    keywords: "手机支架,手机壳,钢化膜,自拍杆,phone stand,case",
  },

  // ── 家居收纳 ────────────────────────────────────────────────
  {
    slug: "home-plastic-storage",
    categorySlug: "home-storage",
    nameZh: "塑料收纳（收纳盒 / 抽屉柜）",
    nameEn: "Plastic storage bins",
    hsCode: "3924.90",
    typicalWeightKg: 0.6,
    typicalVolumeCbm: 0.02,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "重金属与邻苯检测；欧盟 EPR 包装注册",
    note: "典型抛货：体积重远大于实重，快递路径会亏掉全部差价，必须海运备货。",
    keywords: "收纳盒,抽屉柜,整理箱,storage box,organizer,bin",
  },
  {
    slug: "home-fabric-storage",
    categorySlug: "home-storage",
    nameZh: "织物收纳（衣物袋 / 挂袋）",
    nameEn: "Fabric storage",
    hsCode: "6307.90",
    typicalWeightKg: 0.3,
    typicalVolumeCbm: 0.004,
    complianceLevel: "ok",
    note: "可压缩包装，抛重比优于硬质收纳，适合空运测款。",
    keywords: "收纳袋,衣物袋,挂袋,storage bag,hanging organizer",
  },
  {
    slug: "home-rack",
    categorySlug: "home-storage",
    nameZh: "厨卫置物架（沥水架 / 免钉架）",
    nameEn: "Kitchen & bath racks",
    hsCode: "7323.93",
    altHsCodes: "3924.10,7615.10",
    typicalWeightKg: 1.2,
    typicalVolumeCbm: 0.012,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "食品接触材料检测（接触餐具部分）",
    note: "不锈钢与铝制品在美国可能触发 Section 232 钢铝加征，需核对 HS 与材质。",
    keywords: "置物架,沥水架,收纳架,rack,shelf,organizer",
  },

  // ── 宠物用品 ────────────────────────────────────────────────
  {
    slug: "pet-feeding",
    categorySlug: "pet",
    nameZh: "喂食（慢食碗 / 自动喂食器）",
    nameEn: "Pet feeding",
    hsCode: "3924.10",
    altHsCodes: "8509.80",
    typicalWeightKg: 0.4,
    typicalVolumeCbm: 0.008,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "FDA 食品接触（美）/ LFGB（德）",
    note: "接触食物必须过食品级材质检测，否则扣关。",
    keywords: "宠物碗,慢食碗,喂食器,pet bowl,feeder,slow feeder",
  },
  {
    slug: "pet-grooming",
    categorySlug: "pet",
    nameZh: "清洁美容（梳 / 洗澡手套 / 除毛）",
    nameEn: "Pet grooming",
    hsCode: "9603.90",
    altHsCodes: "3924.90,8214.90",
    typicalWeightKg: 0.12,
    typicalVolumeCbm: 0.0008,
    complianceLevel: "ok",
    note: "轻小件，快递测款成本低，社媒易出爆款。",
    keywords: "宠物梳,洗澡手套,除毛,grooming,brush,deshedding",
  },
  {
    slug: "pet-leash",
    categorySlug: "pet",
    nameZh: "牵引与穿戴（牵引绳 / 胸背带）",
    nameEn: "Leashes & harnesses",
    hsCode: "4201.00",
    altHsCodes: "6307.90",
    typicalWeightKg: 0.2,
    typicalVolumeCbm: 0.0015,
    complianceLevel: "warn",
    requiredCerts: "拉力/承重测试报告",
    note: "承重失效会导致宠物走失的责任索赔，务必留存测试报告。",
    keywords: "牵引绳,胸背带,狗绳,leash,harness,collar",
  },
  {
    slug: "pet-toys",
    categorySlug: "pet",
    nameZh: "宠物玩具（耐咬 / 发声）",
    nameEn: "Pet toys",
    hsCode: "9503.00",
    altHsCodes: "4016.99",
    typicalWeightKg: 0.15,
    typicalVolumeCbm: 0.002,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "若被判为儿童玩具需 CPC / EN71",
    note: "⚠️ 宠物玩具与儿童玩具的界限由海关判定，外观接近儿童玩具时会被要求 CPC，无证扣关。",
    keywords: "宠物玩具,耐咬,发声玩具,pet toy,chew toy",
  },

  // ── 运动健身 ────────────────────────────────────────────────
  {
    slug: "fitness-yoga",
    categorySlug: "fitness",
    nameZh: "瑜伽（垫 / 砖 / 拉力带）",
    nameEn: "Yoga mats & blocks",
    hsCode: "9506.91",
    altHsCodes: "3918.90,4008.21",
    typicalWeightKg: 1.8,
    typicalVolumeCbm: 0.018,
    logisticsFlag: "volumetric",
    complianceLevel: "ok",
    note: "🔴 体积重杀手：快递计费重可达实重 2~3 倍，只能海运。拉力带注意天然橡胶过敏标注。",
    keywords: "瑜伽垫,瑜伽砖,拉力带,yoga mat,yoga block,resistance band",
  },
  {
    slug: "fitness-strength",
    categorySlug: "fitness",
    nameZh: "力量（哑铃 / 壶铃 / 负重）",
    nameEn: "Dumbbells & kettlebells",
    hsCode: "9506.91",
    altHsCodes: "7325.99",
    typicalWeightKg: 8,
    typicalVolumeCbm: 0.006,
    logisticsFlag: "heavy",
    complianceLevel: "ok",
    note: "🔴 重货，仅海运且需核算尾程派送附加费；铸铁件在美国可能触发 Section 232。",
    keywords: "哑铃,壶铃,负重,dumbbell,kettlebell,weight",
  },
  {
    slug: "fitness-recovery",
    categorySlug: "fitness",
    nameZh: "恢复（筋膜枪 / 泡沫轴）",
    nameEn: "Recovery (massage gun, foam roller)",
    hsCode: "9019.10",
    altHsCodes: "8479.89,3926.90",
    typicalWeightKg: 1.1,
    typicalVolumeCbm: 0.005,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "CE, FCC, UN38.3；宣称疗效则触发医疗器械监管",
    note: "⚠️ 一旦在listing宣称治疗效果，会被归为医疗器械（FDA / MDR），监管成本剧增。只能宣称按摩放松。",
    keywords: "筋膜枪,泡沫轴,按摩枪,massage gun,foam roller",
  },

  // ── 美妆工具 ────────────────────────────────────────────────
  {
    slug: "beauty-brushes",
    categorySlug: "beauty-tools",
    nameZh: "刷具（化妆刷 / 粉扑）",
    nameEn: "Makeup brushes & sponges",
    hsCode: "9603.30",
    altHsCodes: "3924.90",
    typicalWeightKg: 0.08,
    typicalVolumeCbm: 0.0008,
    complianceLevel: "ok",
    note: "动物毛刷需注意部分国家的动植物检疫申报。",
    keywords: "化妆刷,粉扑,美妆蛋,makeup brush,sponge,blender",
  },
  {
    slug: "beauty-devices",
    categorySlug: "beauty-tools",
    nameZh: "美容仪器（洁面仪 / 射频 / 脱毛）",
    nameEn: "Beauty devices",
    hsCode: "8509.80",
    altHsCodes: "8543.70",
    typicalWeightKg: 0.3,
    typicalVolumeCbm: 0.0015,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "FDA（美）/ CPNP、MDR（欧）/ CE, FCC, UN38.3",
    note: "⚠️ 射频与光电类极易被判医疗器械；IPL 脱毛在多国需医疗器械注册。",
    keywords: "洁面仪,美容仪,射频,脱毛仪,beauty device,IPL",
  },
  {
    slug: "beauty-hair",
    categorySlug: "beauty-tools",
    nameZh: "毛发造型（卷发棒 / 直发器）",
    nameEn: "Hair styling tools",
    hsCode: "8516.32",
    typicalWeightKg: 0.5,
    typicalVolumeCbm: 0.003,
    complianceLevel: "warn",
    requiredCerts: "CE-LVD, FCC, PSE(日), 各国插头制式",
    note: "⚠️ 加热类电器电压制式必须匹配目的国（110V/220V），错发等于全批报废。",
    keywords: "卷发棒,直发器,电吹风,curling iron,straightener,hair dryer",
  },

  // ── 母婴用品 ────────────────────────────────────────────────
  {
    slug: "baby-feeding",
    categorySlug: "baby",
    nameZh: "喂养（辅食碗 / 吸盘碗 / 餐具）",
    nameEn: "Baby feeding",
    hsCode: "3924.10",
    typicalWeightKg: 0.25,
    typicalVolumeCbm: 0.003,
    complianceLevel: "block",
    requiredCerts: "FDA 食品接触（美）/ LFGB（德）/ EN 14372",
    note: "🔴 婴儿入口制品，无食品接触检测报告禁止备货。硅胶件需过挥发物测试。",
    keywords: "辅食碗,吸盘碗,婴儿餐具,baby bowl,suction plate,feeding set",
  },
  {
    slug: "baby-educational",
    categorySlug: "baby",
    nameZh: "早教益智（积木 / 拼图 / 感统）",
    nameEn: "Educational toys",
    hsCode: "9503.00",
    typicalWeightKg: 0.7,
    typicalVolumeCbm: 0.009,
    logisticsFlag: "volumetric",
    complianceLevel: "block",
    requiredCerts: "CPC + CPSIA（美）/ EN71-1,2,3 + CE（欧）/ ST（日）",
    note: "🔴 全品类监管最严：无 CPC 亚马逊直接下架并可能冻结资金；小零件需过窒息测试。无证禁止进入候选池。",
    keywords: "积木,拼图,早教,益智玩具,building blocks,puzzle,montessori",
  },
  {
    slug: "baby-safety",
    categorySlug: "baby",
    nameZh: "安全防护（门卡 / 桌角 / 插座塞）",
    nameEn: "Baby proofing",
    hsCode: "3926.90",
    typicalWeightKg: 0.1,
    typicalVolumeCbm: 0.001,
    complianceLevel: "block",
    requiredCerts: "CPC + CPSIA（美）/ EN71（欧）",
    note: "🔴 儿童用品一律需 CPC。插座类还需电气安全认证。",
    keywords: "门卡,桌角,插座塞,安全锁,baby proof,corner guard,outlet cover",
  },

  // ── 户外露营 ────────────────────────────────────────────────
  {
    slug: "outdoor-lighting",
    categorySlug: "outdoor",
    nameZh: "照明（营地灯 / 头灯 / 手电）",
    nameEn: "Outdoor lighting",
    hsCode: "8513.10",
    typicalWeightKg: 0.3,
    typicalVolumeCbm: 0.0018,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "CE, FCC, UN38.3（含电池）",
    note: "内置锂电需 UN38.3；可更换电池款空运更灵活。",
    keywords: "营地灯,头灯,手电筒,camping light,headlamp,flashlight",
  },
  {
    slug: "outdoor-cookware",
    categorySlug: "outdoor",
    nameZh: "炊具（便携炉 / 户外餐具）",
    nameEn: "Camp cookware",
    hsCode: "7615.10",
    altHsCodes: "7323.93",
    typicalWeightKg: 0.8,
    typicalVolumeCbm: 0.005,
    complianceLevel: "warn",
    requiredCerts: "食品接触检测；燃气类需 CE-GAR",
    note: "⚠️ 含燃气部件属危险品运输，须走危包专线；铝制品可能触发 Section 232。",
    keywords: "便携炉,户外餐具,炊具,camp stove,cookware,mess kit",
  },
  {
    slug: "outdoor-gear",
    categorySlug: "outdoor",
    nameZh: "装备（折叠桌椅 / 吊床 / 天幕）",
    nameEn: "Camp furniture & shelters",
    hsCode: "9401.79",
    altHsCodes: "6307.90,6306.22",
    typicalWeightKg: 3.5,
    typicalVolumeCbm: 0.035,
    logisticsFlag: "heavy",
    complianceLevel: "warn",
    requiredCerts: "静态承重 + 跌落测试；纺织品阻燃（部分州）",
    note: "🔴 大件重货仅海运。承重失效直接导致人身伤害索赔，测试报告必须留存。",
    keywords: "折叠椅,折叠桌,吊床,天幕,camping chair,hammock,tarp",
  },
  {
    slug: "outdoor-drinkware",
    categorySlug: "outdoor",
    nameZh: "水具（保温杯 / 水袋 / 滤水器）",
    nameEn: "Drinkware & hydration",
    hsCode: "9617.00",
    altHsCodes: "3924.10,8421.21",
    typicalWeightKg: 0.45,
    typicalVolumeCbm: 0.003,
    complianceLevel: "warn",
    requiredCerts: "FDA / LFGB 食品接触；加州 Prop 65",
    note: "⚠️ 保温杯内胆与涂层需过重金属迁移；滤水器若宣称净化效果需额外认证。",
    keywords: "保温杯,水袋,滤水器,水壶,tumbler,water bottle,hydration",
  },

  // ── 厨房小工具 ──────────────────────────────────────────────
  {
    slug: "kitchen-cutting",
    categorySlug: "kitchen",
    nameZh: "切削（刨丝器 / 切菜器 / 削皮）",
    nameEn: "Cutting & slicing tools",
    hsCode: "8210.00",
    altHsCodes: "8205.51,8214.90",
    typicalWeightKg: 0.25,
    typicalVolumeCbm: 0.0015,
    complianceLevel: "warn",
    requiredCerts: "食品接触检测；锋利件需警示标",
    note: "刀具类在部分国家有入境管制与年龄限制销售要求。",
    keywords: "刨丝器,切菜器,削皮刀,grater,slicer,peeler",
  },
  {
    slug: "kitchen-bakeware",
    categorySlug: "kitchen",
    nameZh: "烘焙（硅胶模具 / 烤垫）",
    nameEn: "Bakeware & silicone mats",
    hsCode: "3924.10",
    altHsCodes: "7323.99",
    typicalWeightKg: 0.2,
    typicalVolumeCbm: 0.004,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "LFGB（德，最严）/ FDA；硅胶需挥发物测试",
    note: "⚠️ 德国 LFGB 对硅胶的要求显著高于 FDA，做欧洲必须按 LFGB 送检。",
    keywords: "硅胶模具,烤垫,蛋糕模,baking mold,silicone mat,bakeware",
  },
  {
    slug: "kitchen-food-storage",
    categorySlug: "kitchen",
    nameZh: "保鲜收纳（保鲜盒 / 抽真空）",
    nameEn: "Food storage & vacuum",
    hsCode: "3923.10",
    altHsCodes: "3924.10",
    typicalWeightKg: 0.5,
    typicalVolumeCbm: 0.012,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "FDA / LFGB 食品接触；欧盟包装 EPR",
    note: "典型抛货；BPA-Free 声明需有检测支撑，虚假声明会被平台处罚。",
    keywords: "保鲜盒,抽真空,食物收纳,food container,vacuum sealer",
  },
  {
    slug: "kitchen-small-appliance",
    categorySlug: "kitchen",
    nameZh: "厨房小电（打蛋器 / 研磨 / 加热）",
    nameEn: "Small kitchen appliances",
    hsCode: "8509.40",
    altHsCodes: "8516.79",
    typicalWeightKg: 0.9,
    typicalVolumeCbm: 0.006,
    complianceLevel: "warn",
    requiredCerts: "CE-LVD/EMC, ETL/UL（美）, PSE（日）, 各国插头",
    note: "⚠️ 电压制式与插头必须匹配目的国；食品接触部件另需 FDA/LFGB。认证成本高，慎做低价款。",
    keywords: "打蛋器,研磨机,电动搅拌,hand mixer,grinder,blender",
  },

  // ── 汽车配件 ────────────────────────────────────────────────
  {
    slug: "auto-interior",
    categorySlug: "auto",
    nameZh: "内饰（手机架 / 脚垫 / 收纳）",
    nameEn: "Auto interior accessories",
    hsCode: "8708.29",
    altHsCodes: "3926.90,5703.30",
    typicalWeightKg: 0.4,
    typicalVolumeCbm: 0.004,
    complianceLevel: "ok",
    note: "脚垫需按车型开模，SKU 深度大、退货率偏高，谨慎铺货。",
    keywords: "车载手机架,脚垫,车载收纳,car mount,floor mat,organizer",
  },
  {
    slug: "auto-electronics",
    categorySlug: "auto",
    nameZh: "车载电子（胎压 / 记录仪 / 车充）",
    nameEn: "Auto electronics",
    hsCode: "9026.20",
    altHsCodes: "8525.80,8504.40",
    typicalWeightKg: 0.35,
    typicalVolumeCbm: 0.002,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "FCC（美）, E-mark（欧）, CE, UN38.3",
    note: "⚠️ 欧盟车载电子无 E-mark 不得销售；记录仪涉隐私法规（德国尤严）。",
    keywords: "胎压监测,行车记录仪,车充,TPMS,dash cam,car charger",
  },
  {
    slug: "auto-emergency",
    categorySlug: "auto",
    nameZh: "应急（搭电宝 / 充气泵 / 拖车绳）",
    nameEn: "Roadside emergency",
    hsCode: "8507.60",
    altHsCodes: "8414.80,5609.00",
    typicalWeightKg: 1.5,
    typicalVolumeCbm: 0.005,
    logisticsFlag: "battery",
    complianceLevel: "warn",
    requiredCerts: "UN38.3, MSDS；搭电宝属大容量锂电",
    note: "🔴 搭电宝容量普遍超空运限值，多数专线拒收，须海运或电池专线。",
    keywords: "搭电宝,充气泵,拖车绳,jump starter,air compressor,tow rope",
  },

  // ── 办公数码 ────────────────────────────────────────────────
  {
    slug: "office-stands",
    categorySlug: "office",
    nameZh: "桌面支架（显示器 / 笔记本架）",
    nameEn: "Monitor & laptop stands",
    hsCode: "9403.20",
    altHsCodes: "8473.30,7616.99",
    typicalWeightKg: 2.2,
    typicalVolumeCbm: 0.01,
    logisticsFlag: "heavy",
    complianceLevel: "warn",
    requiredCerts: "承重测试；气压杆需疲劳测试",
    note: "重货走海运；铝合金件在美国可能触发 Section 232 钢铝加征。",
    keywords: "显示器支架,笔记本支架,升降架,monitor stand,laptop stand",
  },
  {
    slug: "office-ergonomic",
    categorySlug: "office",
    nameZh: "人体工学（脚踏 / 腰靠 / 坐垫）",
    nameEn: "Ergonomic accessories",
    hsCode: "9403.20",
    altHsCodes: "3926.90,9404.90",
    typicalWeightKg: 1.0,
    typicalVolumeCbm: 0.015,
    logisticsFlag: "volumetric",
    complianceLevel: "warn",
    requiredCerts: "泡棉阻燃（加州 TB117）；不得宣称医疗矫正",
    note: "⚠️ 记忆棉属抛货；宣称矫正脊椎会触发医疗器械监管，只能宣称舒适支撑。",
    keywords: "脚踏,腰靠,坐垫,记忆棉,footrest,lumbar support,seat cushion",
  },
  {
    slug: "office-desk-lighting",
    categorySlug: "office",
    nameZh: "桌面照明（台灯 / 屏幕挂灯）",
    nameEn: "Desk lighting",
    hsCode: "9405.21",
    altHsCodes: "9405.42",
    typicalWeightKg: 0.62,
    typicalVolumeCbm: 0.004,
    complianceLevel: "warn",
    requiredCerts: "CE-LVD/EMC, ERP 能效, FCC, PSE(日)",
    note: "⚠️ 欧盟 ERP 能效标签与 EPR 注册缺一不可；蓝光与频闪指标是差异化卖点。",
    keywords: "台灯,屏幕挂灯,护眼灯,desk lamp,monitor light bar",
  },
];
